---
- hosts: workstations
  roles:
     - mariadb
  remote_user: byron
  become: yes
  become_method: sudo
  tasks:
  - name: Install ssh key for user byron
    authorized_key:
      user: byron
      key: "{{ lookup('file', '/home/byron/.ssh/id_rsa.pub')}}"
      state: present

  - name: Add atom ppa repository
    apt_repository:
      repo: 'ppa:webupd8team/atom'
      codename: 'xenial'
      state: present

  - name: Install atom
    apt:
      name: atom
      state: present

  - name: Install git
    apt:
      name: git
      state: present

  - name: Install curl
    apt:
      name: curl
      state: present

  - name: Get nodejs from Ubuntu binary distributions repository
    shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

  - name: Install nodejs
    apt:
      name: nodejs
      state: present

  - name: Install Clementine
    apt:
      name: clementine
      state: present
